### PR TITLE
Mocap Optitrack

### PR DESCRIPTION
**Pull request by costashatz**
Mocap Optitrack launch files and configuration files.

### CODE REVIEW

**Comment by jbmouret** [comment]
**OK for me**

**Comment by dogoepp** [comment]
Was it tested on Pexod and Omnigrasper ?

**Comment by costashatz** [comment]
> Was it tested on Pexod and Omnigrasper ?

It was tested with Pexod. @fedeallocati could test it with omnigrasper.

**Comment by costashatz** [comment]
@dogoepp Now using python class! :smiley:

**Comment by dogoepp** [comment]
As soon as we agree on https://github.com/resibots/hexa_control/pull/9, we can merge

**Comment by dogoepp** [comment]
Cool ! thanks :)

**Comment by dogoepp** [comment]
**OK** to merge

**Pull request merged**
